### ISSUE TITLE
There may be a licensing problem

### ISSUE THREAD

**Issue by pmario** [forwardemail/font-awesome-assets#1]
Hi folks, 

Nice work, but I do think there is a licensing problem with the assets: see: http://fontawesome.io/license/

While the CSS stuff is MIT, the `/fonts/` directory is not. It's http://scripts.sil.org/OFL . Having a very short look a your code, it seems there is a problem.

Your license is MIT, but I don't see a different one for the [extracted svg's](https://github.com/crocodilejs/font-awesome-assets/tree/master/media/rainbow). Is it possible to convert SIL to MIT? ... please check!

@davegandy what do you think?

---

I'm not a lawyer, so the above may be wrong.

**Comment by niftylettuce** [comment]
I merely have Font Awesome as a dependency.

**Comment by pmario** [comment]
Hmmm, IMO https://github.com/crocodilejs/font-awesome-assets/tree/master/media/rainbow is a complete republishing, with MIT and not SIL? .

**Comment by niftylettuce** [comment]
Oh wow I did not know that got published.  damn.  Taking that down, was
only used to generate the image.  Nice catch man ahaha

**Comment by niftylettuce** [comment]
@pmario do I just change the license on this project, or make a note about the fonts being licensed under SIL OFL 1.1?  I'll make a note in the Readme right now though.

**Comment by niftylettuce** [comment]
@pmario see this https://github.com/crocodilejs/font-awesome-assets/commit/3dc66595e5714567cf48a32872c35de91432076f

**Comment by pmario** [comment]
For me, it looks much better now. ... I'd like to see what @davegandy says.
