### ISSUE TITLE
Consider adding a cli tool

### ISSUE THREAD

**Issue by wmartins** [forwardemail/font-awesome-assets#2]
Hey guys, first of all, this project is really nice, it is fitting all my needs by now.

I was just wondering, it would be really nice if I could use this project via a cli tool. For example:

``` bash
font-awesome-assets svg home 128 "#000" > home.svg
```

(or something like that)

So, every time I need to create (or even recreate, due to new version) an icon, I wouldn't need to code any javascript.

Also, I think I would be able to add your project in my `package.json` and just add an `npm script` to encapsulate that cli, and just use like this:

``` bash
npm run gen:icon svg home 128 "#000" > home.svg
```

What do you think about that?

**Comment by vutran** [comment]
I love this idea. This could live in a separate CLI module and may actually work better with a shorter bin name like `fa` or `faa`.

Ideally, we should be setting those parameters via flags since it would be difficult for a user to remember the exact order of the options...

``` bash
$ faa home

$ faa home --color "#000" > home.svg

$ faa home --size 128 > home.svg

$ faa home --type svg > home.svg

$ faa home --type png > home.png
```

**Comment by niftylettuce** [comment]
Just submit a pull request and use `crocodile` CLI for inspiration at https://github.com/crocodilejs/crocodile-cli

**Comment by niftylettuce** [comment]
Anyone interested in adding this as a PR? @wmartins @vutran

**Comment by niftylettuce** [comment]
PR welcome
