### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by HyramTang** [forwardemail/font-awesome-assets#4]
I get a error information ```error:not found``` when I run ```npm install -s font-awesome-assets```

**Comment by niftylettuce** [comment]
Should be OK - let me know otherwise @HyramTang - try again?

**Comment by HyramTang** [comment]
I'm sorry，I used other way to solve this，thank you~:smile:

**Comment by niftylettuce** [comment]
No problem - are you still using this package?  Curious how you are!

**Comment by HyramTang** [comment]
I found another project，
here is address： https://github.com/Pythonity/font-awesome-to-png
