### ISSUE TITLE
Email Client Support ?

### ISSUE THREAD

**Issue by mr-White** [forwardemail/font-awesome-assets#6]
This does not work on many email clients. SVG is hardly supported, and base64 inline png's is hit or miss. The following is based on using the `png3x()` function

Breaks on Gmail (Chrome), Inbox by Gmail, Outlook on Windows (2013 and 2016), Android 6.0, AOL Mail (Explorer - adds a border)

Works on iPhone, iPad, Apple Mail 10 & 11, Outlook.com (Explorer), 

There's a good 1/3 email users that this does not work with according too https://emailclientmarketshare.com/

Maybe we should just use old remote url png's and stop base64 in lining them? Building emails that work on this ancient email clients is the worse head-ache ever

**Comment by niftylettuce** [comment]
you need to use the nodemailer base64tos3 plugin

im going to enforce it in the next release

**Comment by niftylettuce** [comment]
@mr-White did you use <https://github.com/ladjs/nodemailer-base64-to-s3> yet?

**Comment by mr-White** [comment]
No, I ended up using regular png images stored on my reverse proxy server that handles static assets

**Comment by niftylettuce** [comment]
closing because the solution already exists https://github.com/ladjs/nodemailer-base64-to-s3
